### ISSUE TITLE
panic: runtime error: index out of range [-1] when running Vale against a file with mixed HTML and MD syntax

### ISSUE THREAD

**Issue by nickvigilante** [jdkato/txtlint#431]
When running Vale against one of the files within our repo, we get the following error:

```
panic: runtime error: index out of range [-1]

goroutine 2515 [running]:
github.com/errata-ai/vale/v2/internal/lint.(*walker).lastTag(...)
	github.com/errata-ai/vale/v2/internal/lint/walk.go:112
github.com/errata-ai/vale/v2/internal/lint.Linter.lintHTMLTokens({0xc003592d40, 0x1, 0x0, 0xc0000ac1b0, 0x1df6e40, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/errata-ai/vale/v2/internal/lint/ast.go:71 +0x154d
github.com/errata-ai/vale/v2/internal/lint.Linter.lintMarkdown({0xc003592d40, 0x1, 0x0, 0xc0000ac1b0, 0x1df6e40, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/errata-ai/vale/v2/internal/lint/md.go:59 +0x194
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFile(0xc000624960, {0xc006c96480?, 0x0?})
	github.com/errata-ai/vale/v2/internal/lint/lint.go:173 +0x2f8
github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1.1({0xc006c96480?, 0x0?})
	github.com/errata-ai/vale/v2/internal/lint/lint.go:118 +0x5b
created by github.com/errata-ai/vale/v2/internal/lint.(*Linter).lintFiles.func1.1
	github.com/errata-ai/vale/v2/internal/lint/lint.go:116 +0x218
```

This happens with the following file in multiple locations: https://github.com/cockroachdb/docs/blob/master/_includes/releases/v21.2/v21.2.0-beta.1.md

The one that I identified Vale doesn't like is as follows (line 166):

```
- An earlier commit changed CockroachDB to use the value of the `IntervalStyle` session var when interpreting interval to string conversions. However, this made `string::interval` and `interval::string` casts have a volatility of "stable" instead of "immutable". This has ramifications for items such as computed columns and check clauses, which cannot use immutable expressions. This means that the particular results returned by these queries can become incoherent when `IntervalStyle` is customized to a different value from its default, `postgres`. In order to provide guardrails against this incoherence, CockroachDB now provides a new, separate configuration knob called `intervalstyle_enabled` that applications can use to "opt in" the ability to customize IntervalStyle:<ul><li>By default, this knob is false and applications cannot customize `IntervalStyle`. Interval to string conversions that are already stored in the schema are unaffected and continue to produce results as per the default style `postgres`.</li><li>When the knob is true, these things happen:</li><ul><li>Apps can start customizing `IntervalStyle` in SQL sessions.</li><li>A SQL session that has a custom `IntervalStyle` will start observing *incoherent results* when accessing tables that already contain a conversion from interval to string.</li></ul></ul>The knob works as follows: The *primary* configuration mechanism is a new [cluster setting](../v21.2/cluster-settings.html) called `sql.defaults.intervalstyle.enabled`. This is the knob that operators and DBAs should customize manually. Then, as a *secondary* configuration mechanism, the value of the [cluster setting](../v21.2/cluster-settings.html) is also copied to each SQL session as a new session var `intervalstyle_enabled`. This is a performance optimization. SQL apps should not modify this session var directly, except for temporary testing purposes. In v22.1, upgrades will be disabled if these stable expressions are found in computed columns, check clauses, etc. [#67792][#67792]
```

- OS - macOS 12.3.1
- Install method: Homebrew
- Vale version 2.16.0

**Comment by jdkato** [comment]
This should be fixed the latest release, v2.16.1, which is out now.
